# Generated by Django 4.0.2 on 2022-02-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_topping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
