# Generated by Django 4.0.2 on 2022-02-28 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.drink'),
        ),
    ]
