# Generated by Django 4.0.2 on 2022-02-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_chart_drink'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
