# Generated by Django 4.0.2 on 2022-03-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_chart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='like',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
